include:
  # This remote project centralize our CI "golden path" https://docs.gitlab.com/ee/ci/yaml/#includefile
  remote: 'https://gitlab.com/drupalspoons/composer-plugin/-/raw/master/templates/.gitlab-ci.yml'

# Sync with Github
sync-with-github:
  before_script:
    - git config --global user.name "${GITHUB_USER_NAME}"
    - git config --global user.email "${GITHUB_USER_EMAIL}"
    - git config --global --add safe.directory /builds/project/omdb_api
  script:
    - git remote add github "${GITHUB_REMOTE_REPOSITORY_URL}"
    - git checkout 1.x-dev
    - git pull origin 1.x-dev
    - git pull github 1.x-dev
    - git status
    - git push https://"${GITHUB_ACCESS_TOKEN}"@github.com/bhanu951/omdb_api.git
