variables:
    DRUPAL_PROJECT_TYPE: modules

include:
  - project: 'comunique/drupal_docker'
    file: '/Drupal_CI/gitlab-ci.yml'

# Sync with Github
sync-with-github:
  before_script:
    - git config --global user.name "${GITHUB_USER_NAME}"
    - git config --global user.email "${GITHUB_USER_EMAIL}"
    - git config --global --add safe.directory /builds/project/${GITHUB_REPOSITORY_NAME}
  script:
    - echo Syncing Code from GITLAB to GITHUB.
    - git remote add github "${GITHUB_REMOTE_REPOSITORY_URL}"
    - git checkout 1.x-dev
    - git pull origin 1.x-dev
    - git status
    - git push https://"${GITHUB_ACCESS_TOKEN}"@github.com/"${GITHUB_USER_NAME}"/"${GITHUB_REPOSITORY_NAME}".git
  rules:
    - if: ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "1.x-dev")
