# Schema for the Update OMDB API Entity Title action.
action.configuration.update_omdb_api_entity_title :
  type: mapping
  label: 'Configuration for "Update OMDB API Entity Title" action'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Title'
    type:
      type: string
      label: 'Type'
    plugin:
      type: string
      label: 'Plugin'

# Schema for the Refresh OMDB API Entity Data action.
action.configuration.refresh_omdb_api_data :
  type: mapping
  label: 'Configuration for "Refresh OMDB API Data" action'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Title'
    type:
      type: string
      label: 'Type'
    plugin:
      type: string
      label: 'Plugin'
