name: pr-review
on:
  push:
    branches: [ 1.x-dev ]
  pull_request:
    branches: [ 1.x-dev ]
  schedule:
    - cron: '0 6 * * 0'
env:
  COMPOSER_MEMORY_LIMIT: -1
  SIMPLETEST_DB: sqlite://tmp/site.sqlite
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"

jobs:
  testing:
    name: Drupal ${{ matrix.drupal-core }} - PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        drupal-core: ['9.4.x', '10.x']
        php-versions: ['7.4', '8.0', '8.1']
        composer-channel: ['stable']
        drupal-release: ['stable']

    steps:
      - name: Checkout Drupal core
        uses: actions/checkout@v2
        with:
          repository: drupal/recommended-project
          ref: ${{ matrix.drupal-core }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, pdo_sqlite

      - name: Update composer
        run: composer --verbose self-update --${{ matrix.composer-channel }}

      - name: Dump composer version
        run: composer --version

      - name: Validate composer.json
        run: composer --verbose validate

      - name: Install dependencies
        run: composer --verbose install

      - run: ./vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite

      - run: ./vendor/bin/drush runserver $SIMPLETEST_BASE_URL &

      - run: until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null

        # https://www.drupal.org/project/drupal/issues/3182653
        # https://www.drupal.org/node/3176567
      - if: ${{ matrix.php-versions == '7.4' }} || ${{ matrix.php-versions == '8.1' }}
        run: composer require phpspec/prophecy-phpunit:^2

      - name: Run a single unit test to verfiy the testing setup.
        run: ./vendor/bin/phpunit -c ./web/core ./web/core/modules/user/tests/src/Unit/UserAccessControlHandlerTest.php

      - run: ./vendor/bin/drush st
